module.exports = {
  up: async (queryInterface) => {
    queryInterface.bulkInsert('options', [{
      optionText: 'I need to check the damage to my ship as quickly as possible. (Climb out the window of you ship)',
      nextEncounter: 2,
      consequence: 'You drop down to the ground and pop the hood of your damaged ship. There’s a small fire burning smouldering and you try to quickly stomp it out with your feet. You are successful, but your shoes are completely melted- you have to discard them.',
      stateChange: 'hasShoes',
      encounterID: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'That’s a lot of smoke- this thing’s about to blow! (Hit the eject button)',
      nextEncounter: 4,
      consequence: 'You strap in and smash that eject button. As you rocket away from your ship in the ejection seat, you realize the damage doesn’t really look that bad. Walking back to your ship, on the other hand, is going to take some time.',
      encounterID: 1,
      stateChange: 'engineDestroyed',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'Those readings may be faulty- better put on a space suit. (Find your space-suit before going outside)',
      nextEncounter: 3,
      consequence: 'You search high and low for your spacesuit, before finally finding it tucked away under your bed behind some questionable reading material. You really should have cleaned the ship before you left. In fact, you really just need to get your shit together in general- just look at this place- it’s disgusting.',
      stateChange: 'hasSpacesuit',
      encounterID: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'There could be a fire down below, better be prepared. (Grab a toolkit and fire extinguisher before heading out)',
      nextEncounter: 2,
      consequence: 'You slide down the fire escape and land on your feet. You pop the hood and immediately blast the engine with your fire extinguisher. As the smoke begins to dissipate, you pat yourself on the back for your good decision making.',
      stateChange: 'hasTools',
      encounterID: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'Not a problem! The warp belt is made of anti-matter, so it shouldn’t be too hard to find for the anti-matter-detector I always keep in my toolkit! (Search the woods for missing parts)',
      nextEncounter: 5,
      consequence: 'Consequence: Armed with your trusty AMD, you stomp off into the dense foliage that surrounds the crash site.',
      encounterID: 2,
      checkState: 'hasTools',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'Option B - Screw stumbling through the woods! I’ll check the ship computer for a nearby town- better to just trade for a new belt. (Go to town)',
      nextEncounter: 6,
      consequence: 'You return to the ship and sure enough, there appears to be a small settlement within walking distance of your downed ship. Funny how that works out right? I mean it’s an entire planet, millions and millions of square miles, and yet you always come down near a settlement. You grab some fliff and head out.',
      stateChange: 'canTrade',
      encounterID: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'Well that’s no biggie, it has to be around here... somewhere. I just need to retrace my steps. (Search the woods for missing parts)',
      nextEncounter: 5,
      consequence: 'Armed with your trusty intuition, you stomp off into the forest… hoping you’ll stumble across your warp belt, somehow. Ah well, stranger things have happened.',
      encounterID: 2,
      checkState: '!hasTools',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'Dammit man, I’m a pilot, not a mechanic! Surely someone in town can fix this piece of junk.',
      nextEncounter: 6,
      consequence: 'After checking the ship computer for coordinates, you make for the nearby town. You grab a few of your more valuable pieces of junk and cross your fingers that the locals have mastered spaceflight, or at least brewing.',
      stateChange: 'canTrade',
      encounterID: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'You figure that your spare parts were scattered around the crash site- spending a few hours combing the woods might be a good idea. (Search the woods for missing parts)',
      nextEncounter: 5,
      consequence: 'You briefly go back aboard to grab your toolkit- you recall having a few tools that may help your search. With a surge of determination, you set off into the woods to find your missing parts. (Go to Premise 5)',
      stateChange: 'hasTools',
      encounterID: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'You feel the creep of despair as you realize you have neither the know-how to repair your ship nor the liquidity to pay for it. You look around, realizing this forest is your new home.',
      nextEncounter: -1,
      consequence: 'As fortune would have it, you find a medium sized ball frequently used in team-based competitive sports involving a net and some sand. With a little creativity, and a lot of desperate isolation, you are able to establish communication with the ball, and live happily ever after.',
      encounterID: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'The town? You have no money, and likely no anatomic commonality with the townsfolk- the ship is a safer bet. (Go to ship)',
      nextEncounter: 3,
      consequence: 'You trek back to your ship through uncharted woods. It takes several hours, but is thankfully uneventful. You are certain more damage will have been done to your ship in the meantime.',
      encounterID: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'That ship has been nothing but trouble since the day you bought it off that shady looking guy from GalaxiesList, might as well just head to town to try and find another beater. (Go to town)',
      nextEncounter: 6,
      consequence: 'Consequence: You head off in the rough direction of town, hoping nothing eats you along the way.',
      encounterID: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'Your AMD starts going crazy- the part must be nearby! (Search carefully for the belt)',
      nextEncounter: -1,
      consequence: 'Huzzah! Your calm, rational approach to this catastrophe has paid off. There, under a fern, as though placed there intentionally by a higher power dictating the course of your playthr- life, is a warp belt. You grab the belt and march back to your ship- you’ll be zipping through hyperspace in no time!',
      encounterID: 5,
      checkState: 'hasTools',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'After hours of fruitless searching you stumble across a solidly built cabin in the woods. There’s really nothing to do but knock on the door and see if they can help... (knock on the door of the mysterious cabin)',
      nextEncounter: -1,
      consequence: 'An aged hermit answers the door, and when it senses your suffering the creature invites you inside. Even though you do not share a common language (or number of limbs) with the old ascetic, the two of you slowly bond. It teaches you about its own enlightenment, as well as the ways of this old forest. Many years later, long after the hermit has passed on and you have inherited its old cabin, you stumble across an aged, decrepit starship crashed in the woods. You run your hand over the rusted body, scarcely able to remember life before the crash.',
      encounterID: 5,
      checkState: 'engineDestroyed',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'You spy a small stream- you could really use a drink... (drink from the stream)',
      nextEncounter: 7,
      consequence: 'You accidentally fall into the stream and find the current surprisingly strong. Your space suit proects you from drowning, and hours later you wash up on an unknown shore...',
      encounterID: 5,
      checkState: 'hasSpacesuit',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'You spy a small stream- you could really use a drink... (drink from the stream)',
      nextEncounter: -1,
      consequence: 'You accidentally fall into the stream and find the current surprisingly strong. Without anything to ensure a continuing oxygen supply, you drown in the powerful current.',
      encounterID: 5,
      checkState: '!hasSpacesuit',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'You notice a tree with some fruit on it- you sure are hungry… (Eat the fruit)',
      nextEncounter: -1,
      consequence: 'Seriously? Eat the fruit? From the alien tree in an alien forest? Did you not read Into the Wild? Not even see the movie? You die.',
      encounterID: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'Go to the Galactic Merchant',
      nextEncounter: -1,
      consequence: 'You find the merchant to be both friendly and understanding of your predicament. He cuts you a deal on some parts that will get your ship flying in no time.',
      encounterID: 6,
      checkState: 'hasShoes',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'Go to the Galactic Merchant',
      nextEncounter: -1,
      consequence: 'As soon as you walk in the owner of the shop appears to go into a fit of rage. You can’t understand exactly what he means, but he points at a sign depicting a shirt and a pair of shoes. Then he pulls an energy weapon from under the cash register. You understand that your lack of shoes has led to a lack of service, and leave.',
      encounterID: 6,
      checkState: '!hasShoes',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'You walked here with hardly any money! (Go to bar)',
      nextEncounter: -1,
      consequence: 'Without anything to trade for new parts, you decide to go blow what you do have drinking whatever passes for beer around these parts. Your spaceship can always wait til tomorrow...',
      encounterID: 6,
      checkState: '!canTrade',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      optionText: 'Lacking much else to go on, you can at least figure that you were carried by the current, which means if you follow the river upstream far enough, you may get back to where you started...',
      nextEncounter: 6,
      consequence: 'You walk for hours, picking your way slowly along the stream. You are uncertain whether you were unconcious through the night, or if it is the same day, or if it is simply always daytime on this planet. Just as the shadows begin to lengthen, you see a town off in the distance. With no better option, you make for the settlement.',
      encounterID: 7,
      createdAt: new Date(),
      updatedAt: new Date(),
    },    
    {
      optionText: 'You almost miss it, but there is a thin plume of smoke rising just over a hill on the other side of the river. You could easily make it...',
      nextEncounter: -1,
      consequence: 'You crest the hill and see grub farm, nestled cozily between several slime fields. You do your best to ignore the smell and approach the house. You are greeted by the many-limbed inhabitants and invited in. Despite having only two arms, you soon display your worth as an excellent bull-grub wrangler. You get a great tan and grow fat eating grub-burgers while your old spacesuit gathers dust in the closet of the spare room the farmers put you up in.',
      encounterID: 7,
      createdAt: new Date(),
      updatedAt: new Date(),
    }]);
  },

  down: async (queryInterface) => {
    await queryInterface.bulkDelete('options', null, {});
  },
};
